create table users (login varbinary(256) not null, passhash varbinary(256) not null, id integer primary key auto_increment not null, time integer not null);
create unique index users_idx on users (login);
create table task_schedule (start_time integer not null, period_time integer not null, user_key integer, data varbinary(1024), id integer primary key auto_increment not null);
create index task_schedule_idx1 on task_schedule(user_key);
create index task_schedule_idx2 on task_schedule(start_time);
create table history(time integer not null, name varbinary(256) not null, data varbinary(16384), user_key integer, id integer primary key auto_increment not null);
create index history_idx1 on history(user_key, time);
create index history_idx2 on history(time);
create table mail_schedule (start_time integer not null, period_time integer not null, user_key integer, data varbinary(1024), id integer primary key auto_increment not null);
create index mail_schedule_idx1 on mail_schedule(user_key);
create index mail_schedule_idx2 on mail_schedule(start_time);
create table billing_transactions(id integer primary key auto_increment not null, time integer not null, amount_before integer, amount integer, amount_after integer, user_key integer, data varbinary(16384));
create index billing_transactions_idx1 on billing_transactions(user_key, time);
create index billing_transactions_idx2 on billing_transactions(time);
create table billing_accounts(user_key integer primary key, last_transaction_id integer, amount integer not null default 0);
create table paypal_transactions(id integer primary key auto_increment not null, user_key integer, time integer not null, invnum integer not null, amt double, currencycode varbinary(4), token varbinary(32));
create unique index paypal_transactions_idx1 on paypal_transactions(token);
create index paypal_transactions_idx2 on paypal_transactions(user_key);
create unique index paypal_transactions_idx3 on paypal_transactions(invnum);
create table paypal_subscriptions(id integer primary key auto_increment not null, user_key integer, time integer not null, billingagreementid varbinary(32));
create unique index paypal_subscriptions_idx1 on paypal_subscriptions(billingagreementid);
create index paypal_subscriptions_idx2 on paypal_subscriptions(user_key);
create table paypal_log(id integer primary key auto_increment not null, user_key integer, time integer not null, correlationid varbinary(32), token varbinary(32), invnum integer, data varbinary(16384));
create index paypal_log_idx1 on paypal_log(user_key);
create index paypal_log_idx2 on paypal_log(time);
create index paypal_log_idx3 on paypal_log(token);
create index paypal_log_idx4 on paypal_log(correlationid);
create index paypal_log_idx5 on paypal_log(invnum);
