#!/bin/sh

### BEGIN INIT INFO
# Provides:          tmp_fixup
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: tmp umount & cleanup
# Description:       umount /tmp & clean it.
### END INIT INFO

umount -f /tmp
rm -Rf /tmp/* /tmp/.??*
